"""Allowing Items to have same names in different stores and quantity

Revision ID: 19dbff4bc125
Revises: 16f65b4d1ab2
Create Date: 2024-05-04 12:27:15.173487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19dbff4bc125'
down_revision = '16f65b4d1ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False, server_default='0'))
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.drop_constraint('items_name_key', type_='unique')
        batch_op.create_unique_constraint('unique_name_store_id', ['name', 'store_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('unique_name_store_id', type_='unique')
        batch_op.create_unique_constraint('items_name_key', ['name'])
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
