"""empty message

Revision ID: 535cb3d86fe0
Revises: 7102720594a8
Create Date: 2024-04-07 12:44:00.555663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '535cb3d86fe0'
down_revision = '7102720594a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint("email", ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("email", type_='unique')
        batch_op.drop_column('email')
    # ### end Alembic commands ###
